---
project_path: /opt/whhato/
web_user: www-data
vhost_template: vhost.conf.j2
tarball_path: "{{ playbook_dir }}/../whhato.tar.gz"
letsencrypt_webroot: /var/www/letsencrypt
acme_challenge_path: /.well-known/acme-challenge/
hostname: whhato.vogelschwarz.de