knpu_oauth2_client:
    clients:
        slack:
            # must be "slack" - it activates that type!
            type: slack
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(OAUTH_SLACK_CLIENT_ID)%'
            client_secret: '%env(OAUTH_SLACK_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_slack_check
            redirect_params: {}

            # whether to check OAuth2 "state": defaults to true
            use_state: true
