whhato:
    path: /whhato/{dateString}
    requirements:
        dateString: '^(\d{2})-(\d{2})-(\d{4})$'
    defaults:
        dateString: ''
        _controller: 'App\Controller\WhhatoController::whatHappenedToday'


index:
    path: /
    defaults: { _controller: 'App\Controller\WhhatoController::index' }

overview:
    path: /overview
    defaults: { _controller: 'App\Controller\WhhatoController::overview' }


connect_slack_start:
    path: /connect/slack
    defaults: { _controller: 'App\Controller\SlackController::connectAction' }

connect_slack_check:
    path: /connect/slack/check
    defaults: { _controller: 'App\Controller\SlackController::connectCheckAction' }

#connect_finished:
#    path: /connect/slack/finished
#    defaults: { _controller: 'App\Controller\SlackController::connectFinishedAction' }
